import React, { useState } from 'react';
import { Download, AlertOctagon, CheckCircle, FileSpreadsheet, FileJson, Database, ChevronDown, Check, Loader2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import clsx from 'clsx';

interface MonitoringResultsProps {
    scanId: string | null;
    cleanCount: number;
    poisonCount: number;
    onClose: () => void;
}

const FORMATS = [
    { id: 'csv', label: 'CSV', icon: FileSpreadsheet },
    { id: 'json', label: 'JSON', icon: FileJson },
    { id: 'xlsx', label: 'Excel', icon: FileSpreadsheet },
    { id: 'parquet', label: 'Parquet', icon: Database },
];

export const MonitoringResults: React.FC<MonitoringResultsProps> = ({ scanId, cleanCount, poisonCount, onClose }) => {
    const [exportFormat, setExportFormat] = useState('csv');
    const [isFormatOpen, setIsFormatOpen] = useState(false);
    const [downloading, setDownloading] = useState(false);

    const handleDownload = async (type: 'clean' | 'poison') => {
        if (!scanId) return;
        setDownloading(true);
        try {
            // Check if file exists/can be generated by hitting the endpoint
            // Since it's a file download, we essentially just navigate to it
            // allowing the browser to handle the download
            const url = `http://localhost:8003/api/monitoring/download?type=${type}&format=${exportFormat}`;
            window.open(url, '_blank');
        } catch (error) {
            console.error("Download failed", error);
        } finally {
            setDownloading(false);
        }
    };

    const SelectedIcon = FORMATS.find(f => f.id === exportFormat)?.icon || FileSpreadsheet;

    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="glass-panel p-6 border-l-4 border-l-cyan-500"
        >
            <div className="flex items-center justify-between mb-6">
                <div>
                    <h3 className="text-xl font-bold text-white">Analysis Complete</h3>
                    <p className="text-sm text-gray-400">Monitoring finished & data separated</p>
                </div>
                <button
                    onClick={onClose}
                    className="text-gray-500 hover:text-white transition-colors text-sm"
                >
                    Dismiss
                </button>
            </div>

            <div className="grid grid-cols-2 gap-4 mb-6">
                <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/20 flex flex-col items-center">
                    <CheckCircle className="text-emerald-400 mb-2" size={24} />
                    <span className="text-2xl font-bold text-white">{cleanCount}</span>
                    <span className="text-xs uppercase tracking-wider text-emerald-400/80">Clean Rows</span>
                </div>
                <div className="p-4 rounded-xl bg-rose-500/10 border border-rose-500/20 flex flex-col items-center">
                    <AlertOctagon className="text-rose-400 mb-2" size={24} />
                    <span className="text-2xl font-bold text-white">{poisonCount}</span>
                    <span className="text-xs uppercase tracking-wider text-rose-400/80">Poisoned Rows</span>
                </div>
            </div>

            <div className="space-y-3">
                <div className="relative z-20">
                    <label className="text-xs text-gray-500 uppercase mb-1 block">Export Format</label>
                    <button
                        onClick={() => setIsFormatOpen(!isFormatOpen)}
                        className="w-full px-3 py-2 bg-dark-900/50 border border-white/10 rounded-lg text-sm text-cyan-400 flex items-center justify-between hover:bg-dark-900 transition-colors"
                    >
                        <span className="flex items-center gap-2">
                            <SelectedIcon size={16} />
                            {FORMATS.find(f => f.id === exportFormat)?.label}
                        </span>
                        <ChevronDown size={14} className={clsx("transition-transform", isFormatOpen && "rotate-180")} />
                    </button>

                    <AnimatePresence>
                        {isFormatOpen && (
                            <motion.div
                                initial={{ opacity: 0, y: 5 }}
                                animate={{ opacity: 1, y: 0 }}
                                exit={{ opacity: 0, y: 5 }}
                                className="absolute left-0 right-0 top-full mt-2 bg-dark-900 border border-white/10 rounded-lg shadow-xl overflow-hidden z-30"
                            >
                                {FORMATS.map(f => (
                                    <button
                                        key={f.id}
                                        onClick={() => {
                                            setExportFormat(f.id);
                                            setIsFormatOpen(false);
                                        }}
                                        className={clsx(
                                            "w-full text-left px-3 py-2 text-sm flex items-center gap-2 hover:bg-white/5 transition-colors",
                                            exportFormat === f.id ? "text-cyan-400 bg-cyan-500/10" : "text-gray-400"
                                        )}
                                    >
                                        <f.icon size={16} />
                                        {f.label}
                                        {exportFormat === f.id && <Check size={14} className="ml-auto" />}
                                    </button>
                                ))}
                            </motion.div>
                        )}
                    </AnimatePresence>
                </div>

                <div className="grid grid-cols-2 gap-3 pt-2">
                    <button
                        onClick={() => handleDownload('clean')}
                        disabled={cleanCount === 0 || downloading}
                        className="flex items-center justify-center gap-2 py-2.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-medium transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {downloading ? <Loader2 className="animate-spin" size={16} /> : <Download size={16} />} Clean
                    </button>
                    <button
                        onClick={() => handleDownload('poison')}
                        disabled={poisonCount === 0 || downloading}
                        className="flex items-center justify-center gap-2 py-2.5 rounded-lg bg-rose-600 hover:bg-rose-500 text-white font-medium transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {downloading ? <Loader2 className="animate-spin" size={16} /> : <Download size={16} />} Poison
                    </button>
                </div>
            </div>
        </motion.div>
    );
};
